### PR TITLE
Added estimated_moving_time

### PR DESCRIPTION
**Pull request by Binghammer**

### CODE REVIEW

**Comment by truizlop** [comment]
Can you provide a link to the official documentation where this field appears?

**Comment by Binghammer** [comment]
https://strava.github.io/api/v3/routes/

**Comment by Binghammer** [comment]
They haven't included it in the example request, but it is in the documentation

**Comment by truizlop** [comment]
Your changes have been included in version 1.3, already released. Thanks for your contribution!

**Pull request merged**
