### PR TITLE
Added deauthorize api

### PR DESCRIPTION
**Pull request by alessionunzi**
I really love this library but given it doesn't offer a way to deauthorise the user and I needed to do that in my app, I've wrote the api and I hope you can merge it to your repository

### CODE REVIEW

**Comment by truizlop** [comment]
Thanks for your Pull Request @alessionunzi. However, in order to accept it, tests must pass at CI. Please, make sure to fix this and I will be happy to merge it.

**Comment by alessionunzi** [comment]
Apologies, I didn't notice the failed test, it's fixed now :)

**Comment by truizlop** [comment]
Your changes are included in version 1.3, already released. Thanks for your contribution!

**Comment by alessionunzi** [comment]
Thank you!

**Pull request merged**
